# Generated by Django 3.1.5 on 2021-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0003_auto_20210515_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
    ]
