# Generated by Django 3.1.5 on 2021-05-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0005_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availibilities'},
        ),
    ]
